urls.py
from whoishere.views import QRView, CheckinView, SuccessView, SplashView, AttendancePollList, AttendancePollCreate, CheckinList
"""
URL configuration for whoishere project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('success/', SuccessView.as_view()),
    path('checkins/', CheckinList.as_view()),
    path('checkin/<slug:slug>/', CheckinView.as_view(), name="checkin-view"),
    path('attendance-polls/', AttendancePollList.as_view()),
    path('qr/<slug:slug>', QRView.as_view()),
    path('create-poll/', AttendancePollCreate.as_view()),
    path('admin/', admin.site.urls),
    path('', SplashView.as_view())
]

models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.core.exceptions import ValidationError
import random
import string
from django.utils.timezone import now
import datetime
import re




class Course(models.Model):
    instructor = models.CharField(max_length=100, null=False, blank=False, default = "W. Andrew Barr")
    semester = models.CharField(max_length=100, null=False, blank=False, choices=[("Spring", "Spring"), ("Fall", "Fall")])
    year = models.PositiveIntegerField( validators=[MinValueValidator(2023), MaxValueValidator(2050)])
    subject_code = models.CharField(default='ANTH', max_length=4, null=False, blank=False, choices=[("ANTH", "ANTH"), ("HOMP", "HOMP")])
    course_number = models.PositiveIntegerField(validators=[MinValueValidator(1001), MaxValueValidator(7000)])
    nickname = models.CharField(null=True, blank=True, max_length=50, help_text="a shorthand way to refer to the course")
    def __str__(self):
        return "{} - {} {} ({}{})".format(self.nickname, self.subject_code, self.course_number, self.semester[0:1], str(self.year)[2:4])


class AttendancePoll(models.Model):
    slug=models.SlugField(max_length=6, null=True, blank=True, help_text="to be auto populated", unique=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    starts = models.DateTimeField(default=now)
    expires = models.DateTimeField(null=True, blank=True, help_text="Leave blank to default to 30 minutes from now")

    def save(self, *args, **kwargs):
        while not self.slug:
            try:
                self.slug=''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
            except:
                pass
        if not self.expires:
            self.expires = self.starts + datetime.timedelta(minutes=30)
        super(AttendancePoll, self).save(*args, **kwargs)

    def is_active(self):
        if self.starts < now() < self.expires:
            return True
        else:
            return False

    def __str__(self):
        return "{} - {}".format((self.expires.strftime("%x")), self.course)


GWID_validator = RegexValidator(r"^G[0-9]{8}$", "Your GWID must be a capital G followed by 8 numbers")
def email_handle_validator(value):
    if re.search("@", value):
        raise ValidationError("Include only the part of your email before the @ symbol")


class Checkin(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    attendance_poll = models.ForeignKey(AttendancePoll, on_delete=models.CASCADE)
    student_last_name = models.CharField(max_length=100, null=False, blank=False)
    student_first_name = models.CharField(max_length=100, null=False, blank=False)
    gw_email_handle = models.CharField(max_length=100, validators=[email_handle_validator], null=False, blank=False, help_text="The part of your GW email address before @gwu.edu")
    GWID = models.CharField(max_length=9, validators=[GWID_validator], null=False, blank=False)

    def __str__(self):
        return "{} -> {} @ {}".format(self.student_last_name, self.attendance_poll.course.__str__(), self.timestamp)

templates/whoishere/attendancepoll_form.html
{% extends 'whoishere/base.html' %}

{% block content %}
    {% load tz %}
    {% timezone "US/Eastern" %}
    <form action="/create-poll/" method="post">
        {% csrf_token %}

     {%  if form.non_field_errors  %}
         <div class="row">
             <div class="col">
                 {{ form.non_field_errors  }}
             </div>
         </div>
     {% endif %}

    <div class="row">
        <div class="col">
        {{ form.course.errors }}
        {{ form.course.label }}
        {{ form.course }}
        </div>
    <div>
    <div class="row">
        <div class="col">
        {{ form.starts.errors }}
        {{ form.starts.label }}
        {{ form.starts }}
        </div>
    <div>
    <div class="row">
        <div class="col">
        {{ form.expires.errors }}
        {{ form.expires.label }}
        {{ form.expires }}
        {{ form.expires.help_text }}
        </div>
    </div>
        <input type="submit" value="Create poll">
    </form>
    {% endtimezone %}
{% endblock %}

templates/whoishere/attendancepoll_list.html
{% extends "whoishere/base.html" %}

{% block content %}
    {% load tz %}
    {% if active_poll_count > 0 %}
        <h3 style="padding-top: 10px;">Currently Active Attendance Polls</h3>
        <div class="row" style="font-weight:bold;">
            <div class="col">Class</div>
            <div class="col">Slug</div>
            <div class="col">Opens</div>
            <div class="col">Closes</div>
        </div>
        {%  for object in object_list %}
            {% if object.is_active %}
        <div class="row">
            <div class="col">
                {{ object.course }}
            </div>
            <div class="col">
                <a href="/qr/{{ object.slug }}" >{{ object.slug }}</a>
            </div>
            {% timezone "US/Eastern" %}
            <div class="col">
                {{ object.starts }} ET
            </div>
            <div class="col">
                {{ object.expires }} ET
            </div>
            {% endtimezone %}
        </div>
            {% endif %}
        {% endfor %}
    {% else %}
        There are no currently active polls
    {% endif %}
{% endblock %}

templates/whoishere/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Who is Here?</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

    <style>
        .errorlist {
            background-color: #f5c20a;
        }

        .errorlist li {
            list-style-type: none;
        }

        .firstrow {
            padding-top: 20px;
        }
        .navbar-brand {
            padding-left: 10px
        }
    </style>
</head>
<body">

<div class="container-fluid">


{% if perms.whoishere.can_edit %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Who Is Here?</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/attendance-polls/">Poll List</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/checkins/">View Checkins</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/create-poll/">Create new poll</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/admin/">Admin</a>
      </li>


    </ul>

  </div>
</nav>
{% endif %}
{% block content %}{% endblock %}
</div> <!-- for container-fluid -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

</body>
</html>

templates/whoishere/checkin_form.html
{% extends 'whoishere/base.html' %}

{% block content %}

        <div class="row">
            <div class="col">
                <h3>Checking in for {{ pollObject.course }} on {{ pollObject.starts | date }}</h3>
            </div>
        </div>

        {% if request.session.last_poll_participated == pollObject.id %}
            <h3>You have already participated in this attendance poll</h3>
        {% else %}
        <form action='/checkin/{{ pollObject.slug }}/' method='post'>
        {% csrf_token %}
            {%  if form.non_field_errors  %}
                <div class="row">
                    <div class="col">
                        {{ form.non_field_errors  }}
                    </div>
                </div>
            {% endif %}
            <div class="row justify-content-start">
                <div class="col-sm-3">First Name</div>
                <div class="col-sm-3">Last Name</div>
            </div>
            <div class="row justify-content-start">
                <div class="col-sm-3">
                    {{ form.student_first_name.errors }}
                    {{ form.student_first_name }}
                </div>
                <div class="col-sm-3">
                    {{ form.student_last_name.errors }}
                    {{ form.student_last_name }}
                </div>
            </div>
            <div class="row justify-content-start" style="padding-top:15px;">
                <div class="col-sm-3">Email handle</div>
                <div class="col-sm-3">GWID</div>
            </div>
            <div class="row justify-content-start">
                <div class="col-sm-3">
                    {{ form.gw_email_handle.errors }}
                    {{ form.gw_email_handle }}
                </div>
                <div class="col-sm-3">
                    {{ form.GWID.errors }}
                    {{ form.GWID }}
                </div>
            </div>
            <div class="row">
                <div class="col">
                    {{ form.attendance_poll }}
                    <input type="submit" value="Check in"/>
                </div>
            </div>
        </form>
    {% endif %}
{% endblock %}

templates/whoishere/checkin_list.html
{% extends "whoishere/base.html" %}

{% block content %}
    {% load tz %}
    {% timezone "US/Eastern" %}
        {%  for object in object_list %}
            {% if object.is_active %}
        <div class="row">
            <div class="col">
                <h3 style="padding-top: 10px;">Who's checked in for {{ object.course.subject_code }} {{ object.course.course_number }} on {{ object.starts | date }}? </h3>
            </div>
        </div>
            <div class="row">
            {% if object.checkin_set.all  %}

            {% for checkin in object.checkin_set.all %}
                    <div class="col-sm-6 col-lg-3">
                        <div class="card" style="padding:3px;">

                        {{ checkin.student_first_name }} {{ checkin.student_last_name }} {{ checkin.timestamp|time }} ET

                        </div>
                    </div>

            {% endfor %}
            {% else %}
                <p>Nobody has checked in yet.</p>
            {% endif %}
            </div>
            {% endif %}
        {% endfor %}
    {% endtimezone %}
{% endblock %}

templates/whoishere/qr.html
{% extends 'whoishere/base.html' %}

{% block content %}
    <div class="row firstrow">
        <div class="col">
            <h3>Check in for {{ object.course }} on {{ object.starts | date }}</h3>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ svg | safe }}
        </div>
    </div>

    <div class="row">
        <div class="col">
            <h3><a href="{{ URL }}"/> {{ URL }}</h3>
        </div>
    </div>



{% endblock %}

templates/whoishere/splash.html
{% extends 'whoishere/base.html' %}

{% block content %}

    <div class="row">
        <div class="col">
            <h3>Who is Here?</h3>
            <p>Welcome! You can't actually do anything from this page.  Ask your instructor for the QR code </p>
        </div>
    </div>
    </div>



{% endblock %}

templates/whoishere/success.html
{% extends  "whoishere/base.html" %}

{% block content %}
        <div class="row">
            <div class="col">
                <h3>Congrats!</h3>
                <p>You have marked yourself as present!</p>
            </div>
        </div>
{% endblock %}